#!/usr/bin/env Rscript

invisible(evalq({
    library('jsonlite')
    library('base64enc')
    library('R6')

    input <- fromJSON(file('stdin'))
    source(paste(input$judge, 'judge.R', sep='/'), chdir=TRUE, local=TRUE)

    start_judgement(input$resources, input$source)
}, envir = new.env(parent = globalenv())))
